### ISSUE TITLE
Migrate unit tests out of the `tests` package and into their respective packages

### ISSUE THREAD

**Issue by leifmadsen** [redhat-service-assurance/smart-gateway#49]
Currently the tests are living in the `tests/internal_pkg/*` directory when they could just live with their packages directly.

Files need to be moves into their corresponding `internal/pkg/{}` directory, and stripped of any external references so that the package isn't imported into the test.

For example, in the `alerts_test.go` file, we need to change:

```
eventAlert := &alerts.Alerts{}
```
--into-->

```
eventAlert := &Alerts{}
```

And them make sure the `alerts` package isn't imported.

**Comment by paramite** [comment]
I don't think this is a good idea. Yes, it makes counting code coverage bit harder, but there are reasons why I moved tests to it's own package:
1. it is the recommended workaround for avoiding falling into cyclic dependencies / import cycles problems
2. test implementer looses access to private logic, so has to think about the tested API more in deep. Also when test of package A breaks, we can be sure that other packages are broken too. On the other side, when you have access to private logic, you can unintentionally workaround issues and hit the bugs in production cycles

Not mentioning that this basically means reverting my previous patches and wasted ~2weeks of my working cycles :)

If we really don't want to have separate tests package, we could create 'test' subpackage in respective packages and put test there, but you will still won't get "&Alerts{}" for which is issue has been probably created.

**Comment by leifmadsen** [comment]
I don't have a strong bias here, I was just going on what is typical in the testing package. I'll close this out since you have a stronger position.

**Comment by csibbitt** [comment]
Glad I saw this conversation :) It's great to have some notes on why things are the way they are!
