### ISSUE TITLE
Events mode causes high CPU usage

### ISSUE THREAD

**Issue by csibbitt** [redhat-service-assurance/smart-gateway#54]
First noticed during performance testing; fully functional SAF, all pods Running and Ready, logs show that cloud1-notify-smartgateway connected to amqp and elasticsearch. No AMQP traffic, the pod is using 2 Cores according to my graphs. Connecting to the top and running `top` shows it bouncing between 100% and 200%.

Reproduced in my local minishift; clean startup from scratch, everything is healthy and quiet; cloud1-notify-smartgateway is burning CPU; top shows it hovering around 60% with occasional spikes to 200%. 

The telemetry smart gateway is using 0% CPU in both cases.

**Comment by leifmadsen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Start looking at ways to understand why the SG in events mode uses so many CPU resources](https://trello.com/c/RwF5mrwl/747-start-looking-at-ways-to-understand-why-the-sg-in-events-mode-uses-so-many-cpu-resources)

**Comment by leifmadsen** [comment]
I've been working on trying to learn a bit about `pprof`, called via the `go tool pprof` command as documented at https://golang.org/pkg/net/http/pprof/

I created this procedure for doing localized testing of the Smart Gateway container image in a running environment (minishift in this case): https://docs.engineering.redhat.com/display/CLOUDOPS/Build+a+new+SAF+component+and+push+to+a+minishift+registry+then+deploy

Once that was done, I made some small modifications to the SG code to enable a listener to expose the profiles so I could run `go tool pprof` within the container running in the environment (and connected to ES, AMQP, etc).

Here is the patch:

```
diff --git a/Dockerfile b/Dockerfile
index 5f5b346..17860c0 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -24,7 +24,7 @@ LABEL io.k8s.display-name="Service Assurance Smart Gateway" \
 
 RUN yum install epel-release -y && \
         yum update -y --setopt=tsflags=nodocs && \
-        yum install qpid-proton-c --setopt=tsflags=nodocs -y && \
+        yum install golang pprof qpid-proton-c --setopt=tsflags=nodocs -y && \
         yum clean all && \
         rm -rf /var/cache/yum
 
diff --git a/cmd/main.go b/cmd/main.go
index 375251d..edd75f1 100644
--- a/cmd/main.go
+++ b/cmd/main.go
@@ -5,6 +5,9 @@ import (
        "os"
        "strings"
 
+       "net/http"
+       _ "net/http/pprof"
+
        "github.com/redhat-service-assurance/smart-gateway/internal/pkg/events"
        "github.com/redhat-service-assurance/smart-gateway/internal/pkg/metrics"
 )
@@ -14,6 +17,10 @@ var eventType = "events"
 
 func main() {
 
+       go func() {
+               log.Println(http.ListenAndServe("localhost:6060", nil))
+       }()
+
        serviceType := getServiceType()
        if serviceType == metricType {
                metrics.StartMetrics()

```

**Comment by leifmadsen** [comment]
After rolling out a new version of the SG with the code changes, I was able to connect to the SG in the minishift environment and run `go tool pprof`:

```
oc exec -it cloud1-notify-smartgateway-3-r98mt -- bash

bash-4.2$ go tool pprof http://localhost:6060/debug/pprof/profile?seconds=30
Fetching profile over HTTP from http://localhost:6060/debug/pprof/profile?seconds=30
Could not use temp dir /pprof: mkdir /pprof: permission denied
Saved profile in /tmp/pprof.smart_gateway.samples.cpu.002.pb.gz
File: smart_gateway
Build ID: d16954de0580693070f46766d4dce8ed025279bc
Type: cpu
Time: Oct 16, 2019 at 7:46pm (UTC)
Duration: 30.19s, Total samples = 22.03s (72.97%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top5 
Showing nodes accounting for 18.83s, 85.47% of 22.03s total
Dropped 7 nodes (cum <= 0.11s)
Showing top 5 nodes out of 13
      flat  flat%   sum%        cum   cum%
     9.13s 41.44% 41.44%     20.98s 95.23%  runtime.selectgo
     3.55s 16.11% 57.56%      3.55s 16.11%  runtime.lock
     3.42s 15.52% 73.08%      3.42s 15.52%  runtime.unlock
     1.47s  6.67% 79.75%      5.02s 22.79%  runtime.sellock
     1.26s  5.72% 85.47%      4.68s 21.24%  runtime.selunlock
```

At this point I now need to read more and learn how to profile Golang code. It's possible I will eventually have to stop because this is not an area I am skilled in.

I'm going to set the card size to a 3 for now and give myself a solid day to look at things since I think I'm a bit ahead in the sprint, but beyond that I'll probably try and tag someone else.

It would be nice to try and figure out what the cause of the high CPU load is though prior to doing a new SG release, which is effectively going to result in people gaining access to the Events support. High CPU load in this area seems like a big deal...

**Comment by leifmadsen** [comment]
@csibbitt and @atyronesmith both pointed me at a `default` clause in a `case` statement in `events.go` which I've now tested and verified was the culprit. Inbound PR soon.
