### ISSUE TITLE
Coveralls push is broken

### ISSUE THREAD

**Issue by paramite** [redhat-service-assurance/smart-gateway#65]
CI jobs are failing with pusshing test coverage statistics to Coveralls. We should fix that.

**Comment by leifmadsen** [comment]
Again? that sucks :(

**Comment by leifmadsen** [comment]
How did you identify that it was broken? I don't think we've done much in terms of commits and pushes to this repo.

**Comment by leifmadsen** [comment]
Well something is broken for sure, just not entirely sure if its coveralls at all:

```
The command "docker run -eCOVERALLS_TOKEN -uroot --network host -it --volume $PWD:/go/src/github.com/redhat-service-assurance/smart-gateway:z --workdir /go/src/github.com/redhat-service-assurance/smart-gateway centos:7 /bin/sh -c 'sh ./build/test-framework/run_tests.sh'" failed and exited with 1 during .
```

**Comment by csibbitt** [comment]
First noticed here: https://github.com/redhat-service-assurance/smart-gateway/pull/61#issuecomment-553943810

```
 *** Uploading coverage report to coveralls
+ goveralls -coverprofile=coverage.out
15:20:57 gitinfo.go:56: exit status 129: error: unknown option `format'
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>...
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>
```

**Comment by leifmadsen** [comment]
Thanks! I assume they have updated the client then and the format is no longer valid...

**Comment by leifmadsen** [comment]
Oh! It's an issue with goveralls compat with the version of `git` on the test node (I'm guessing). The error is because of this:

https://github.com/mattn/goveralls/blob/master/gitinfo.go#L27-L36

I don't have time to fix it right now... was hoping it was a syntax problem that I could resolve quickly, but no such luck.

**Comment by leifmadsen** [comment]
I think I fixed this recently. Closing.
